Manual v0.8.0 Release
copilot-jp/project-sprint pull request #132
Opened 2020-08-23 13:46 UTC by Satoshi-Matsumoto

- Tutorial v0.8.0
- Manual v0.8.0
ほか、CODEとの必要な導線整理

2020-08-24 02:49 UTC, kikuchiharuma requested changes

2020-08-24 02:49 UTC, kikuchiharuma commented on ja/manual/tutorial/section3/section3-2.md
> +優先順位をつけた結果、当日話し合うことができないアジェンダは、次週以降のアジェンダに持ち越しましょう。こうしたアジェンダがあるとき、アジェンダトリアージは、次の3つのなかから優先順位づけをすることになります。
次週とは限らず、話す場としてはミーティングという表現が良いと思うので、「次回以降のミーティングに持ち越しましょう」が良いと思いました

2020-08-24 03:08 UTC, kikuchiharuma commented on ja/manual/tutorial/section5/section5-1.md
> +プロジェクトスプリントは[CC BY-SA 4.0ライセンス](https://projectsprint.org/LICENCE)でサポートされるオープンなメソッドです。このメソッドは、**Project Sprint Contributers** と呼ばれる有志のユーザーによって定義 / 改善を繰り返してかたちづくられています。
CCライセンスでサポートされる、という表現は意味がよくわかりませんでした。
CCライセンスで提供される、の方が良いように思います。

2020-08-24 03:31 UTC, kikuchiharuma commented
@Satoshi-Matsumoto セマンティクス的な要請なのですが、各文書の見出し(Yaml Front Matterになっている箇所)が、大きな文書のカテゴリになっていて、ページが持つ意味を示す見出しとしては括りが大きすぎ、また文書ごとの差を表現できていないという問題があると思いました。こんな感じです。

プロジェクトスプリント チュートリアル <- h1相当 (Yaml Front Matter指定のページタイトル)
準備しよう <- h2相当 (セクション内の文書は共有する見出し)
プロジェクトのゴールとマイルストーンを設定する <- h3相当 (文書固有の見出し)

例えばシェアしたときに、どの文書のog:titleも「プロジェクトスプリント チュートリアル」になってしまいます。
提案としては、それぞれ、

プロジェクトスプリント チュートリアル <- 省略 
準備しよう (1/2) <- h1相当 (Yaml Front Matter指定のページタイトル)
プロジェクトのゴールとマイルストーンを設定する <- h2相当 (文書固有の見出し)

とするか、

プロジェクトスプリント チュートリアル <- 省略 
準備しよう <- h1相当 (Yaml Front Matter指定のページタイトル)

として、セクションの文書を統合してしまっても良いかなと思いました。

2020-08-24 03:36 UTC, kikuchiharuma commented on ja/manual/tutorial/section3/section3-2.md
> +- ミーティング前に提出のあったアジェンダ
@Satoshi-Matsumoto この箇所、リストでなくなっていたのでとりあえず直しましたが、多分本来の意図は前段の番号を残して1行だけ引用したいんですよね。markdownだと数字を変えてもNumbered Listは1から始まってしまうので、数字を残したければこの辺りを試してください。

https://github.com/gettalong/kramdown/issues/211#issuecomment-256508905

2020-08-25 10:19 UTC, motoi commented on ja/manual/tutorial/section1/section1-2.md
> +一方チーミングの「理想の状態」とは、チームメンバー同士の果たすべき役割（これを、ロールと呼びます）についての期待値がそろっている状態です。言い換えると、あるチームメンバーが「あの人はこれをやってくれるだろう」と考えたとき、そのチームメンバーも「これは私がやるべきことだ」と考えている状態です。チーミングの「理想の状態」には、明確な形がありません。なぜなら「ここまで達成したら理想のチームだ！」という
ロールの期待値がそろっている状態、だけと言い切ってよいんだっけ。これは会話したい！

2020-08-25 10:23 UTC, motoi commented on ja/manual/tutorial/section2/section2-1.md
> +プログレスドメインの「理想の状態」とは、プロジェクトのゴールが達成されている状態です。そのため、まずは将来達成したいプロジェクトのゴールを定義し、そのために必要な成果物と、成果物をつくっていくための道のり（これを、マイルストーンと呼びます）を設定します。
> （これを、マイルストーンと呼びます）

これはどこからどこまでを指してマイルストーンと呼んでいるのか読み取れなかった。

2020-08-25 11:24 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section1/section1-2.md
> +一方チーミングの「理想の状態」とは、チームメンバー同士の果たすべき役割（これを、ロールと呼びます）についての期待値がそろっている状態です。言い換えると、あるチームメンバーが「あの人はこれをやってくれるだろう」と考えたとき、そのチームメンバーも「これは私がやるべきことだ」と考えている状態です。チーミングの「理想の状態」には、明確な形がありません。なぜなら「ここまで達成したら理想のチームだ！」という
最終的な結果だけとしてあらわすのであれば、チーミング = 期待値の一致。プログレス = ゴールやマイルストーンの達成、になると思います。ただし、その前提や途中経過として、心理的な安全性や継続的改善アプローチが行われているという経緯があるわけで、その内容を入れないと確かに誤解を生むのかもしれないという気がしました。

なので、どちらの「理想の状態」にもかかる前提として、心理的安全性・継続的改善アプローチがあるんだよ、と手厚くかくのがようにトライしてみます。

2020-08-25 11:30 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section1/section1-2.md
> +一方チーミングの「理想の状態」とは、チームメンバー同士の果たすべき役割（これを、ロールと呼びます）についての期待値がそろっている状態です。言い換えると、あるチームメンバーが「あの人はこれをやってくれるだろう」と考えたとき、そのチームメンバーも「これは私がやるべきことだ」と考えている状態です。チーミングの「理想の状態」には、明確な形がありません。なぜなら「ここまで達成したら理想のチームだ！」という
…と思ったものの、これは明確にCODEと乖離している部分になるので、先にCODEの中で解く議論として進めましょう、後ほど、issue化します。

2020-08-27 11:30 UTC, kikuchiharuma commented on ja/manual/tutorial/section5-1.md
> +#### ユーザーコミュニティ
これ、弁護士さんの確認間に合わないとすると、書けるのはもう少し先になりますね。
@motoi 見込みどうでしょう。

2020-08-27 11:31 UTC, kikuchiharuma commented
この件は直接修正しました。みてください。 @Satoshi-Matsumoto 

> @Satoshi-Matsumoto セマンティクス的な要請なのですが、各文書の見出し(Yaml Front Matterになっている箇所)が、大きな文書のカテゴリになっていて、ページが持つ意味を示す見出しとしては括りが大きすぎ、また文書ごとの差を表現できていないという問題があると思いました。こんな感じです。
> 
> プロジェクトスプリント チュートリアル <- h1相当 (Yaml Front Matter指定のページタイトル)
> 準備しよう <- h2相当 (セクション内の文書は共有する見出し)
> プロジェクトのゴールとマイルストーンを設定する <- h3相当 (文書固有の見出し)
> 
> 例えばシェアしたときに、どの文書のog:titleも「プロジェクトスプリント チュートリアル」になってしまいます。
> 提案としては、それぞれ、
> 
> プロジェクトスプリント チュートリアル <- 省略
> 準備しよう (1/2) <- h1相当 (Yaml Front Matter指定のページタイトル)
> プロジェクトのゴールとマイルストーンを設定する <- h2相当 (文書固有の見出し)
> 
> とするか、
> 
> プロジェクトスプリント チュートリアル <- 省略
> 準備しよう <- h1相当 (Yaml Front Matter指定のページタイトル)
> 
> として、セクションの文書を統合してしまっても良いかなと思いました。

2020-08-28 10:09 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +ゴールは、最初のドラフトは誰がつくってもかまいませんし、一人でもつくっても複数で作ってもかまいませんが、通常は、
最初からみんなで作ることを推奨したい。インセプションデッキをみんなでつくる感覚と同じで、プロジェクトのみんなのものになるから。

2020-08-28 10:10 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +マイルストーンも、ゴール同様最初のドラフトは誰がつくってもかまいませんし、一人でつくっても複数でつくってもかまいません。
これも目的と同じで最初からみんなで作ることを推奨したい。

2020-08-28 10:11 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +設定したゴールとマイルストーンは、いつでもチームメンバーが参照できる状態にしておきます。
みんなが理解しやすいように極力シンプルにすることも書きたい。

2020-08-28 10:13 UTC, motoi commented on ja/manual/tutorial/section2-2.md
> +- それぞれのメンバーは、どのような人ですか？例えばスキルセットは、どのようなものがありますか？これまえにどのような仕事にかかわってきましたか？
>これまえ
これまで？

2020-08-28 10:22 UTC, motoi commented on ja/manual/tutorial/section2-3.md
> +まず、ミーティングは定例会議である必要があります。これには理由が二つあります。一つ目は、ある程度以上の複雑性があるプロジェクトでは、都度チームメンバーを招集していては必要な議論がタイムリーにできない可能性があるということ。二つ目は、週次や月次といった一定の期間における開催とすることで、プロジェクトの状態を定期的にチェックし、必要な時に見直すことができるということです。
会議 → ミーティング
に言葉をそろえたい。

2020-08-28 10:25 UTC, motoi commented on ja/manual/tutorial/section2-3.md
> +なお、各ミーティングの参加者はアジェンダに応じて必要十分な程度でかまいません。ここでいう必要十分とは、アジェンダに関して網羅的に議論でき（＝「誰かがいないから今日はこの話ができないね」ということがないようにする）、また議論をもとに正式な意思決定ができること（＝「誰かがいないから今日はこの話は決まらないね」ということがないようにする）を意味しています。
割と色んな資料で10人以上にはしないでねとは言っている。多くなると議論の場ではなく共有の場になるので目的が変わるから。

2020-08-28 10:52 UTC, motoi commented on ja/manual/tutorial/section3-1.md
> +なお、プロジェクトスプリントではモデレーターとアクセラレーターの二つをまとめてファシリテーターと定義しています。
ほとんどがファシリテーターとしてしか使わないので、上の説明の部分で
ファシリテーターの機能の説明としてモデレーターとアクセラレーターがあるみたいな方がわかりやすいとおもいました。

2020-08-28 10:53 UTC, motoi commented on ja/manual/tutorial/section3-1.md
> +毎回のミーティングが始まる前には、予め各チームメンバーがアジェンダを提出します。アジェンダには、少なくとも次のような内容が含まれている必要があります。
>予め
あらかじめ
開いたほうが読みやすいのは開きたい。

2020-08-28 10:57 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +ミーティングの最初に、タスク確認とテンショントリアージを行ってください。これらを通じて、前回のミーティングから今回のミーティングまでに、実際の作業や気持ちの面のそれぞれで起こったことについて、チームメンバー同士でアップデートを行い、必要であれば新たなタスク化/アジェンダ化して対処することができます。
タスク確認というよりは、タスクの実行結果の報告、と書いたほうが分かりやすいかなと。
もしくはタスクの状況報告とかかな。

2020-08-28 10:59 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +#### タスク確認とテンショントリアージ
あとここでマイルストーンを確認するのも重要な作業ではある。

2020-08-28 21:02 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
何のためにタスク確認とテンショントリアージとマイルストーン確認を行うかというと、今日のMTGで話すべきことを決める材料になるから、です。
そのあたりのサマリを最初にかいたほうが読みやすいのではないか。

2020-08-28 21:03 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
なぜタスク確認が必要かというと、実行期間中に行われたことを共有することで、今日のMTGではなすべきこと、次のMTGまでのアクションをつくる材料になるから、みたいな目的を書いたほうがよいのでは？

2020-08-28 21:08 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +テンションとは、「プロジェクトを過ごす中で他のメンバーに伝えたい違和感」のことです。具体的には、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などのことを指します。
トリアージとはこういう意味ってのを書いてもよいかも。

ここもなんでテンショントリアージが必要かという目的を書いてもよいかもと思いました。
いつものGoogleドライブの
テンショントリアージ（言葉の定義と進め方）
をアップデートしているので読んでもらい目的を補足してもらってもよいかも。

2020-08-28 21:09 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +なお、すでに予めタスクとしてリストアップされていたり、アジェンダとして提出されていた場合は、ここでさらに追加する必要はありません。
> なお、すでに予めタスクとしてリストアップされていたり、アジェンダとして提出されていた場合は、ここでさらに追加する必要はありません。

この文章が必要な意味がちょっとわかりませんでした。なくても成立する？あえて書く必要があるのであればおしえてくださいー。

2020-08-28 21:10 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
冒頭にアジェンダトリアージとは、今日のMTGで話すべき内容を参加者全員でアジェンダを編集することで決定することです、みたいな目的が1文あるだけで分かりやすくなる気がしました。

2020-08-28 21:13 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
>その分他のアジェンダの時間を調整するか、場合によっては他のアジェンダを次回以降に繰り越すようにしてください。
会議自体を延長する、という選択肢もあるなとおもいました。

2020-08-28 21:15 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
この時にマイルストーンを改めてみることも非常に有効な場合があります。

2020-08-28 21:17 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
> リストアップしたタスクには、タスクと期限を明確にするようにしてください。

タスクという言葉が被っているのでわかりづらいなとおもいました。
「タスクと期限」をもう少し書いてもよいかなと思いました。
具体的な行動内容、担当者、期限、ということかなとおもいます。

2020-08-28 21:20 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +----
このセクションに
ミーティングのテンプレがあるとよいよ
という話をいれてもよいんじゃないかなとおもいました。
だいたい定例によってミーティングの冒頭と終結で型が決まっていくので、最初はよちよちとはじめるけど、最終的には型ができて、その型があるほうがスムースで効率よくなるよ、みたいなことに言及してもよいとおもいます。

2020-08-28 21:22 UTC, motoi commented on ja/manual/tutorial/section4-1.md
> +プロジェクトスプリントではミーティングを通じて継続的にプロジェクトの進め方を改善すること（最適化）を目指しています。これらの最適化のため取り組みを総称して「継続的改善アプローチ」と呼んでおり、これはさらに「テンショントリアージ」と「振り返り」という二つの取り組みに分けられます。
> 「継続的改善アプローチ」

どこかの記述ではこれに「ロール確認」も入ってなかったっけ？全体で統一されていればそれでよいです。

2020-08-28 21:23 UTC, motoi commented on ja/manual/tutorial/section4-1.md
> +そのため、振り返りはテンショントリアージと違いある程度まとまった期間をおいて実施するものであり、またその分必要な時間もテンショントリアージよりも長くなります。ただし、この「まとまった期間」は、「何かのマイルストーンが終わったあとに実施する」といったようなものではなく、「何週間おき」「何か月おき」といったような定期的な時間で設定してください。これは、最適化ができずにマイルストーンがいつまでも達成で
> テンショントリアージと違いある程度まとまった期間

テンショントリアージと違い、ある程度まとまった期間

とかで読点を入れるか、表現変えるかなんかして読みやすくしたい

2020-08-28 21:25 UTC, motoi commented on ja/manual/tutorial/section4-1.md
> +そのため、振り返りはテンショントリアージと違いある程度まとまった期間をおいて実施するものであり、またその分必要な時間もテンショントリアージよりも長くなります。ただし、この「まとまった期間」は、「何かのマイルストーンが終わったあとに実施する」といったようなものではなく、「何週間おき」「何か月おき」といったような定期的な時間で設定してください。これは、最適化ができずにマイルストーンがいつまでも達成で
> 「何かのマイルストーンが終わったあとに実施する」

これも推奨しています。定期的な実施と、フェーズの終わりでの実施の両方を推奨してます。
実践ログ入れの中のファイルの
プロジェクトスプリントにおけるチームビルディング継続的改善アプローチ
を参照くださいー。

2020-08-28 21:48 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +設定したゴールとマイルストーンは、いつでもチームメンバーが参照できる状態にしておきます。
しょっちゅう聞かれるのでtipsに書いてもよいかもしれないけどマイルストーンの書き方のコツは

・みんなが理解しやすいように極力シンプルに書く
に加えて
・それを見ている同じチームのメンバーが自分で意思決定して動くことができる粒度にする
・それを見ている同じプロジェクトの他のチームメンバーが、そのチームと足並みを揃えることができる材料とできる

です。これは本当によく聞かれるのでどこかに書いてもよいかも。

2020-08-28 21:51 UTC, motoi commented on ja/manual/tutorial/section4-3.md
> +ロールの確認をするべきタイミングは、次のような時です。
ロールに関するテンションがあがるよね、という話題もあるとおもうけど、なんか文脈違うきもしたので、書くかどうかは判断おまかせします！

2020-08-28 22:03 UTC, motoi commented on ja/manual/tutorial/section5-1.md
> +#### ユーザーコミュニティ
@kikuchiharuma 
弁護士さんにPJS関連について定期的に時間もらっているのが月に1回で、次回は9/25なのです。いまSlackで聞いているけど、たぶん次のMTGで詳しく話をききながら判断させて、ということになるとおもいます。

私のそもそものスタンスですが、菊地さんが調べて考えてくれてこれでよいと判断されたということがあったので、この記述でいったん公開でよいとおもっています。
弁護士さんに一応きいてみようかな的なノリではありました。私もサトマツさんもあの場で違和感なかったですし。

なので公開でよいとおもっています。

ですが菊地さんとして弁護士さんの見解をもらってから公開したい、という気持ちになっているのであれば、9月末の公開に調整させてください。

といことで菊地さんどうでしょう？

2020-08-28 22:06 UTC, motoi commented on ja/manual/tutorial/section5-1.md
> +
これ以下のかかわり方はREADMEとかのCODEの時にコントリビューター向けにつくったファイルにリンクさせて一元管理したほうが良いんじゃないでしょうか。
ダブル面T根になりそうな予感がする。
あとチュートリアルなのにCODEへのコントリビューションについて述べてる感じが違和感ある。
あとサービス名は
Super Good Meetings
ではなくスペーストルツメで
SuperGoodMeetings
です！（細かい）

2020-08-28 22:21 UTC, motoi commented on ja/manual/tips/index.md
> +6. [ ロールシートの利用](tips6.md)
[　ロール…
と頭にスペースがはいっているのでトルツメ

2020-08-28 22:26 UTC, motoi commented on ja/manual/tips/tips1.md
> +#### トラック - ゴールに対して複線的なマイルストーンの進行をしたいときの考え方
@kikuchiharuma さん、ここは figureおじさんの絵が登場したほうが良いんじゃないかしらと文章を読んで思いましたよ。
かつてSuperGoodMeetingsの画面説明資料ようにつくったパワポ芸はこちら。
![image](https://user-images.githubusercontent.com/680855/91619744-ebfa4580-e9c8-11ea-8d98-b2533ea2c02e.png)

2020-08-28 22:31 UTC, motoi commented on ja/manual/tips/tips1.md
> +
@Satoshi-Matsumoto さん、SGMsの説明するときにトラックの概念がよくわからん、といわれるのでこのあたりの説明をするのはとてもよいとおもうんですけど、まずプロジェクト、トラック、マイルストーン、フェーズの全体の関係を図で理解してから、各用語の説明を始めたほうがわかりやすいとおもいました。

かつてSuperGoodMeetingsの画面説明資料ようにつくった定金スライド芸はこちら。
![image](https://user-images.githubusercontent.com/680855/91619744-ebfa4580-e9c8-11ea-8d98-b2533ea2c02e.png)
これでだいぶ理解してもらえる率があがった。
これがあってから各用語に移るほうが良いんじゃないかなと。

@kikuchiharuma さん、このセクションは figureおじさんの絵が登場したほうが良いんじゃないかしらと文章を読んで思いましたよ。

2020-08-28 22:32 UTC, motoi commented on ja/manual/tips/tips1.md
> +
絵が欲しい！

2020-08-28 22:44 UTC, motoi commented on ja/manual/tips/tips1.md
> +#### イベント - 作業の直接の進行とは関係ない重要行事
> 作業の直接の進行とは関係ない

この表現に違和感があります。
イベントの私のイメージでは「あまりころころと期日が変わらない、プロジェクトメンバー全員が知っておく必要がある、あるタイミングで発生するおおきな出来事」という感じでしょうか。語彙力。。。

なのでイベントは各トラックのマイルストーンに非常に大きく関係してくるものを書くし、各メンバーの作業もマイルストーンもイベントも見ます。
（ゆくゆくは各トラックにもイベントを設定できるようにSGMsもするかもしれない）

その作業に対して関係性は強いものも弱いものもあるけど、逆に作業に関係しそうな出来事だけを入れるイメージです。

例示してみるね。
関係あるイベントの例だと、SuperGoodMeetingsのプレスリリースを2021年4/1にド派手に行ってイベントも開催するぜ会場も抑えたし！みたいなとき、ビックサイトのプロジェクトマネジメント展に出展するので 10月1日から10月7日まではビックサイトで展示するぜ！とかの期間モノがあったりするとき、みたいな感じです。
それをPJSのイベントに書いておいて、あビックサイトで展示あるならこんなことをうちらのトラックではやらなきゃね、とか全トラックメンバーが気にする感じです。

あんまり関係ないイベントの例だと、コパのプロダクトのリリースに向けて、コパの9/20の創立記念日にイベントやるけど、そこでなんか発表する可能性あるかもね、という話がでたからとりあえずイベントにいれておくみたいな弱めの関連でもいれることはあるとおもいます。

みたいな使い方になっております。

サトマツさんが例に出してくれている役員会や商戦期も書くと思いますねえ。良い例だと思います。でもこれも私のイメージでは「作業の直接の進行と関係ない」といえない感じがしています。表現の問題かしら。

2020-08-28 22:51 UTC, motoi commented on ja/manual/tips/tips1.md
> +しかし、プロジェクトでのコミュニケーション上は、いま自分たちは何をしているのか？ということを表現できたほうが便利です。このそれぞれを、「フェーズ」と呼びます。つまり、この例では、
自分たちのチームメンバー、他のチームメンバーにとって、何をいまやっているのか、がわかるラベリングが重要みたいな記述がほしいです。マイルストーンマップで全体がどういううごきをしているのか極力分かりやすくなることが目的なので。

2020-08-28 22:53 UTC, motoi commented on ja/manual/tips/tips10.md
> +Section3-2で解説したように、ミーティング開始時にはテンショントリアージを実施します。これによって、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などを共有し、解決のためのアクションにつなげることができるようになります。
> ミーティング開始時
開始時というご語弊があるきがしていて、ミーティングの前半に行われることがおおい、というニュアンスかもしれません。報告をしっかりやってテンションあつめる会議とかだと半分ぐらいのタイミングもあるし。

2020-08-28 22:54 UTC, motoi commented on ja/manual/tips/tips10.md
> +  - 他メンバーへのタスクのリクエスト
他メンバーではなく、自分のタスクの場合もある（ファシに問われて、あ自分のタスクだなときづくこともある）
なので「タスクのリクエスト」でよいとおもいます。

2020-08-28 22:56 UTC, motoi commented on ja/manual/tips/tips10.md
> +テンショントリアージは、次のような手順で実施します。
これはあくまでも一例で、チームによって最適になるようにカスタマイズしていってちょ、みたいな記述もほしいかも。いろんなところでやってみてやっぱり結構変えることが多いので。ホラクラシーは組織におけるプロセスが完全にきまってるのであの選択肢に固定でよいとおもうんだけど、PJSはプロジェクトの進め方とか構造が変わることがおおいのでカスタマイズが必要になってきます。

2020-08-28 23:01 UTC, motoi commented on ja/manual/tips/tips2.md
> +
ここも概念図があったほうがわかりやすいかとおもいました。

2020-08-28 23:04 UTC, motoi commented on ja/manual/tips/tips3.md
> +成果物は、マイルストーン完了の際につくられているべきもののことを指します。成果物はアウトカムによって構成されています。
このセクション全体おもしろいけど、どういう流れでアウトカムって設定したのでしょうか。アウトカムは自分では使ったことがない概念なので、このチップスが必要だとおもった理由がしりたい。

2020-08-28 23:07 UTC, motoi commented on ja/manual/tips/tips9.md
> +一般的な「振り返り」の手法は様々なものがありますが、ここでは比較的簡単に導入でき、汎用性も高い二つの手法を例として紹介します。
チーミングよりの振り返りとしてYWTがあるなとおもっていて。PJSが全体的にチーミングに弱めってことがあるならYWTは入れてもよいかもしれない。

2020-08-28 23:08 UTC, motoi commented on ja/manual/tips/tips9.md
> +プロジェクトスプリントにおける振り返りとはチームメンバーが過去のプロジェクトの内容についてレビューする取り組みです。
レビューした結果、何になる取り組みになるのかまで書きたい。
プログレス、プロセス、チームの改善につながるってことかなと。
って書くまでもない、自明すぎってことで書いてないのかしら。

2020-08-28 23:14 UTC, motoi commented on ja/manual/tips/tips7.md
> +アジェンダ管理に不可欠な前提がミーティング中の時間を的確に把握することです。オンライン / オフラインいずれの場合も、ミーティングに参加しているチームメンバーが時間を把握できるよう、目に入る位置にタイマーを把握しましょう。
> タイマーを把握しましょう。
配置？

2020-08-28 23:15 UTC, motoi commented on ja/manual/tips/tips7.md
> +なお、ミーティング中は「いま何時か」ではなく、「このミーティングはあとどのくらいあるのか」「このアジェンダにあとどれくらい時間をかけられるのか」を把握することが必要になるため、現在時刻を示す時計よりもタイマーを利用したほうがよいとされています。
> 現在時刻を示す時計よりもタイマーを利用したほうがよいとされています。

時計がないとミーティングの全体時間を過ぎちゃうので、両方が用意されるのがよいです。

2020-08-28 23:19 UTC, motoi commented on ja/manual/tips/tips7.md
> +なおここでいうとホワイトボードはオフライン会議における物理的なものに限りません。オンライン会議用のホワイトボードツールもありますので、そういったものを利用してもかまいませんし、むしろ保存のしやすさという点ではこちらのほうが優れている場合もあります。
ここの項目名を「ホワイトボード」とするとちょっとアナログなKOKUYOの1畳サイズのものが浮かんじゃうので変えてもよいかも。
手書き入力による認識合わせツール
リアルタイムに反映される認識合わせツール
みたいな感じかな。これだとイメージできないかな。。。

最近テレワークが増えてきて、手書き入力じゃなくて、ワードの議事録をデカデカ表示するスタイルをみて、手書きじゃなくてもよいかもなーとおもったこともあり。

ということで
リアルタイムに反映される認識合わせツール（手書きだとなおよし）
みたいな感じに調整できればとおもいました。

2020-08-28 23:20 UTC, motoi commented on ja/manual/tips/tips4.md
> +ここで話す内容は一般的にプロジェクト管理で語られる要素と大きく異なりません。しかし、プロジェクトスプリントでは、それらの要素すべてにおいて、「コミュニケーションの透明性をいかに担保するか」という点を中心に考えるべきです。
>コミュニケーションの透明性をいかに担保するか

ここに情報の透明性のニュアンスも含まれている？情報が透明であるからこそコミュニケーションができるとおもっているのでプライオリティ的には情報が上かなと読んでおもいました。

2020-08-28 23:21 UTC, motoi commented on ja/manual/tips/tips4.md
> +- ファイル管理: プロジェクトメンバーが誰でもアクセスできるファイル管理環境を用意しましょう。
表現の問題だけど
全員が同じ情報にアクセスできるようにする
みたいなニュアンスの方が近いかなと思いました。

2020-08-28 23:22 UTC, motoi commented on ja/manual/tips/tips4.md
> +- スケジュール管理: スケジュール調整に必要な限りで、メンバー間の個人カレンダーを共有するようにしましょう。これは、メールなどによって都度日程調整をするのではなく、チームメンバーのスケジュール状況が一か所に集まっており、必要な人が必要なときに見に行ける環境を意味しています。
> 必要な人が必要なときに見に行ける環境

見に行くという表現がちょっとしっくりきませんでした。
ミーティングは非常に重要な認識合わせツールなので、そのミーティングを設定・変更をコスト少なくするためにカレンダーをみんなで共有して調整しやすくしたい、
みたいなニュアンスです。

2020-08-28 23:27 UTC, motoi commented on ja/manual/tips/tips4.md
> +その他、プロジェクトスプリントにおける3つのドメインおいて必要とされる環境 - マイルストーン管理（プログレス）、ロール管理（チーミング）、ミーティング管理（プロセス）、については、それぞれ別Tipsをご参照ください。
ここで管理ということばが3つ連続ででてきて初めて大きく違和感になったんだけど、すごくPJSぽくない言葉だなとおもった「管理」。
管理という言葉だと誰か一人がコントロールする感が大きい。
なんか言葉開発したいけど、共同管理の方がまだよい。
なんか言葉のニュアンスもみんなでみようぜ！みたいなことにしたいなー。

2020-08-28 23:34 UTC, motoi commented on ja/manual/tips/tips5.md
> +ただし、次に紹介するようなロールについては実務上よく使われるであろう予め用意されており、特にプロジェクトスプリントを始めて導入する場合、これらのロールを利用することによって導入をスムーズに行うことができます。
> ただし、次に紹介するようなロールについては実務上よく使われるであろう予め用意されており、特にプロジェクトスプリントを始めて導入する場合、これらのロールを利用することによって導入をスムーズに行うことができます。

なんか日本語へん？
言いたいことは
・実務上必要なロールは定義しているから必要であれば使ってね
・初めてのひとはロール設定するとはじめやすいよ
だよね？なんかこの文章は読みづらかった。
あと 始めて って 初めて の方がよいのかな？

2020-08-29 12:39 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3/section3-2.md
> +優先順位をつけた結果、当日話し合うことができないアジェンダは、次週以降のアジェンダに持ち越しましょう。こうしたアジェンダがあるとき、アジェンダトリアージは、次の3つのなかから優先順位づけをすることになります。
@kikuchiharuma 
たしかに。
e22dc15619a1998bea968c3aa8df68af9a5ef11a
でなおしました。

2020-08-29 12:42 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section5/section5-1.md
> +プロジェクトスプリントは[CC BY-SA 4.0ライセンス](https://projectsprint.org/LICENCE)でサポートされるオープンなメソッドです。このメソッドは、**Project Sprint Contributers** と呼ばれる有志のユーザーによって定義 / 改善を繰り返してかたちづくられています。
@kikuchiharuma 
ライセンスとサポートってなんなら並列的な表現になっちゃいますね。
01dbb941b1579ffc0c3994b1afcab94ce1f4442a
で修正しました。

2020-08-29 12:58 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3/section3-2.md
> +- ミーティング前に提出のあったアジェンダ
@kikuchiharuma 
ありがとうございます！もらったリンクの方法で直せました。
b3fb0172dc0ca2e4fe540597199ede20d4fbaa0f

2020-08-29 13:16 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section1/section1-2.md
> +一方チーミングの「理想の状態」とは、チームメンバー同士の果たすべき役割（これを、ロールと呼びます）についての期待値がそろっている状態です。言い換えると、あるチームメンバーが「あの人はこれをやってくれるだろう」と考えたとき、そのチームメンバーも「これは私がやるべきことだ」と考えている状態です。チーミングの「理想の状態」には、明確な形がありません。なぜなら「ここまで達成したら理想のチームだ！」という
これはissue化したのでこの場ではResolveとします。
https://github.com/copilot-jp/project-sprint/issues/137

2020-08-29 13:20 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2/section2-1.md
> +プログレスドメインの「理想の状態」とは、プロジェクトのゴールが達成されている状態です。そのため、まずは将来達成したいプロジェクトのゴールを定義し、そのために必要な成果物と、成果物をつくっていくための道のり（これを、マイルストーンと呼びます）を設定します。
@motoi 
41defc03e6700ecdedef5ab3fcf835f4b5d00c41
こんな感じで明確になりますかね？

2020-08-29 13:24 UTC, Satoshi-Matsumoto commented
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/pull/132#issuecomment-681891617
これはばっちり直ってました！ありがとうございます。

2020-08-29 13:32 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-1.md
> +ゴールは、最初のドラフトは誰がつくってもかまいませんし、一人でもつくっても複数で作ってもかまいませんが、通常は、
@motoi ここなんですが実際の実務でもみんなでイチからつくるようになってますか？（実際には誰かがドラフトを最初につくるようになってませんか？

当然プロジェクトみんなのものになるので、最終的な状態としては

> ただし、最初のドラフトができたあとは、それがチームメンバー全員に明文化されたかたちで共有され、全員が納得している状態になるまで議論されなければいけません。

となるべきなのですが、実務として本当に最初からみんなでつくるのが現実的なのかは気になりました。

私がメソッドチームでマイルストーンをつくるときに持っている感覚は、「誰かがラフでも素案を作ってきて、みんなで敲く」なので、むしろそれが例外的なんであれば修正まったく問題ないのですが、そこだけ一応確認したいです。

2020-08-29 13:32 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-1.md
> +マイルストーンも、ゴール同様最初のドラフトは誰がつくってもかまいませんし、一人でつくっても複数でつくってもかまいません。
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479650273

をご参照ください。マイルストーンに関してもゴールと同じです。

2020-08-29 13:44 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-1.md
> +設定したゴールとマイルストーンは、いつでもチームメンバーが参照できる状態にしておきます。
@motoi 
内容的にはTipsよりはマニュアル上に入れたい内容です。

> ・みんなが理解しやすいように極力シンプルに書く
> ・それを見ている同じチームのメンバーが自分で意思決定して動くことができる粒度にする

この二つは修正反映しました。
68b14c45a9965929d93a4be0fac5ea57ac3bdde3

ただ、

> ・それを見ている同じプロジェクトの他のチームメンバーが、そのチームと足並みを揃えることができる材料とできる

これは「足並みを揃える」がちょっとぼやっとしていてわかりそうで腹落ちしないなと。もう少し具体的に表現する or 具体例をもらうことはできますか？
（もらったもの次第で、すぐに伝わりきらなそうであればissue化して今回は見送ります）

2020-08-29 13:44 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-2.md
> +- それぞれのメンバーは、どのような人ですか？例えばスキルセットは、どのようなものがありますか？これまえにどのような仕事にかかわってきましたか？
タイポですね。これまで、です。
492cd621735ccaa1f2c8baa742b01fa643b9f8e6

2020-08-29 13:53 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-3.md
> +まず、ミーティングは定例会議である必要があります。これには理由が二つあります。一つ目は、ある程度以上の複雑性があるプロジェクトでは、都度チームメンバーを招集していては必要な議論がタイムリーにできない可能性があるということ。二つ目は、週次や月次といった一定の期間における開催とすることで、プロジェクトの状態を定期的にチェックし、必要な時に見直すことができるということです。
@motoi 
全編通して揃えました。ちょっとやりすぎかとおもいましたが会議室もミーティングルームに直しました。
cc2b4d545ed4128e7faf7989fb81f82738251694

2020-08-29 14:01 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-3.md
> +なお、各ミーティングの参加者はアジェンダに応じて必要十分な程度でかまいません。ここでいう必要十分とは、アジェンダに関して網羅的に議論でき（＝「誰かがいないから今日はこの話ができないね」ということがないようにする）、また議論をもとに正式な意思決定ができること（＝「誰かがいないから今日はこの話は決まらないね」ということがないようにする）を意味しています。
@motoi これはissueにしましょう。

> 割と色んな資料で10人以上にはしないでねとは言っている。多くなると議論の場ではなく共有の場になるので目的が変わるから。

このコメントだと、共有の場としてのミーティングはProject Sprintでは存在しない、という風に読めるのですが、それはそれでよいんでしたっけ？という点がまず気になったポイントです。

3人だろうと10人以上であろうと必要十分な人数であれば出席しておくべきなので、どういう目的の会議であればだいたい10人もいらないでしょ、となり、どういう目的の会議であれば10人超えるよね、という話になるのかと。

そのうえで、10人以上の会議であれば共有目的だし、かつそういう目的の会議はProject Sprintでは認めない、となって初めて10人以上にしないでね、といえると思います。

てことで、issue化して深堀りしましょう。

2020-08-29 14:04 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-3.md
> +なお、各ミーティングの参加者はアジェンダに応じて必要十分な程度でかまいません。ここでいう必要十分とは、アジェンダに関して網羅的に議論でき（＝「誰かがいないから今日はこの話ができないね」ということがないようにする）、また議論をもとに正式な意思決定ができること（＝「誰かがいないから今日はこの話は決まらないね」ということがないようにする）を意味しています。
@motoi 
https://github.com/copilot-jp/project-sprint/issues/138
issue化したことをご確認いただいたら、Resolveお願いします。

2020-08-29 14:17 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-1.md
> +なお、プロジェクトスプリントではモデレーターとアクセラレーターの二つをまとめてファシリテーターと定義しています。
@motoi 
7fbf8cded734213109a0c2687c39f9331cdbc2ba
こんな感じで。モデレーターやアクセラレーターを使ったほかの表現も、ファシリテーターを軸とした表現に変えました。

2020-08-29 14:18 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-1.md
> +毎回のミーティングが始まる前には、予め各チームメンバーがアジェンダを提出します。アジェンダには、少なくとも次のような内容が含まれている必要があります。
@motoi 
マニュアル全編通して直しておきました。
47b6746160633dd71bec5e830ef355675bd8b385

2020-08-29 14:21 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +ミーティングの最初に、タスク確認とテンショントリアージを行ってください。これらを通じて、前回のミーティングから今回のミーティングまでに、実際の作業や気持ちの面のそれぞれで起こったことについて、チームメンバー同士でアップデートを行い、必要であれば新たなタスク化/アジェンダ化して対処することができます。
@motoi 
直近のMTGでよく使われている表現を参考に、「タスクの進捗報告」としました。意味的にも問題ないと思います。
318446cae224783d38fa36eeecbd2ccf2e03c2f7

2020-08-29 14:33 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +#### タスク確認とテンショントリアージ
@motoi 
マイルストーン確認の頻度を確認したいのですが、これって毎ミーティングやる必要のあるものでしょうか？
毎回のことでなければ、「改善しよう」のsection 4-2「プロジェクトのゴールとマイルストーンを見直す」のところに書いているので。

事実上毎週やっているのであれば、毎回これのどれかに該当するという解釈であって、タスク確認（進捗報告）やアジェンダトリアージと並列の活動ではないと思います。

> 1. あるマイルストーンが達成されたとき
> 2. あるマイルストーンが予定通りに達成されないことが明らかになったとき（予定よりも遅い場合、早い場合のいずれも含む）
> 3. プロジェクトのゴールに対してあるマイルストーンが適切ではないことが明らかになったとき
> 4. プロジェクトのゴールが変わったためマイルストーンも変える必要が出てきたとき
> 5. その他何らかの理由でチームメンバーがマイルストーンを見直したほうがよいと考えたとき

メソッド上、何が違和感のある部分かというとsection3-2はプロセスの内容について記述しているのですが、マイルストーン確認は明らかにプログレスのステータスを確認する活動なので、これを毎週のものとするならチーミングのステータス確認であるロール確認も毎週やらないといけないのでは？という発想になって、それは違うんじゃないか、と思うのです。（伝わってますかね・・・？）

2020-08-29 14:35 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +#### タスク確認とテンショントリアージ
@motoi 
と、いうわけでこちらissueとして別深堀りさせてください。
https://github.com/copilot-jp/project-sprint/issues/139
issue化されているのを確認したらResolveお願いします。

2020-08-29 14:42 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
@motoi 
サマリ一応あったんですけど分かりにくかったですかね。該当部分を修正してみました。
318446cae224783d38fa36eeecbd2ccf2e03c2f7

2020-08-29 14:42 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
@motoi 
318446cae224783d38fa36eeecbd2ccf2e03c2f7
こっちと重複してしまうのでこちらはいらないかと思いました。

2020-08-29 14:55 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +テンションとは、「プロジェクトを過ごす中で他のメンバーに伝えたい違和感」のことです。具体的には、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などのことを指します。
@motoi 
トリアージの意味は確かに入れたほうがいいですね。追記しました。
770b314ba5779f5ea6e5e9a0641a6c9585c05441

テンショントリアージの目的もこの中で語ってみましたがどうでしょうか。

GDriveにあげていただいているテンショントリアージの目的は、マニュアルの記載内容の粒度感的にはいらないかなー、と思ったのですがどうでしょう。

2020-08-29 14:57 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +なお、すでに予めタスクとしてリストアップされていたり、アジェンダとして提出されていた場合は、ここでさらに追加する必要はありません。
@motoi 
テンショントリアージとかやってて、とりあえず出すんだけど「あ、それ実はもうアジェンダにしてあります」みたいなことってないですかね？または、「でもそれも次回の～～で対応することになってるよね」みたいなやつ。
そこをあえて書きました。タスク確認（進捗報告）だと頻発するからすっと入ってくると思うのですが、こちらもあるとは思います。

2020-08-29 15:00 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
@motoi 
まさにそうですね。こんな感じでどうでしょう。
40a91d6772dc777442c5649b3b96ea688e986a0f

2020-08-29 15:06 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
@motoi 
確かに。
931348f2736c3e89db44b647c91fa291d33958c0
でなおしました。

2020-08-29 15:08 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
これは
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479655319
と同じで、ミーティングのクロージング時に有効なときはsection4-2でのマイルストーンの見直しタイミングのどれかにあたっている場合だと思うので、そちらの記述で完結させたほうがいいと思います。

下記でまとめて話しましょう。issue化されているのを確認したらResolveしてください。
https://github.com/copilot-jp/project-sprint/issues/139

2020-08-29 15:10 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +
@motoi 
たしかに、めちゃくちゃわかりにくくなってましたね。。。
いただいたコメントそのまま使わせてもらいました。
7b998f571ee7e2dba87ded082608265d83cf00ac

2020-08-29 15:25 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +----
@motoi 
これぜひ入れたいんですけどもう少し膨らましてTipsネタにするべきもののような気がします。
（マニュアルにこれだけ入れるとなんか中途半端になりそう、具体例と一緒に語りたい、という意味で。）

issue化するのでそちらに今までの具体例とか書いていただくこと可能ですか？
それをもとに書いてみて、反映は次回リリース以降にします。

2020-08-29 15:27 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section3-2.md
> +----
https://github.com/copilot-jp/project-sprint/issues/140
にissue化したので、まずこれを確認いただいたらこちらはResolveしてください。

そちらの進行は別途アサインなど進めます。

2020-08-29 15:33 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section4-1.md
> +プロジェクトスプリントではミーティングを通じて継続的にプロジェクトの進め方を改善すること（最適化）を目指しています。これらの最適化のため取り組みを総称して「継続的改善アプローチ」と呼んでおり、これはさらに「テンショントリアージ」と「振り返り」という二つの取り組みに分けられます。
@motoi 継続的改善アプローチにはロール確認は入りません。そして、入らないでいいと思います。

CODE上下記のような整理になっていて

- 継続的改善アプローチ=> プロセスの一部。最適化ための活動。最適化の対象はチーミング / プログレス / プロセス。
- マイルストーン確認 => プログレスのステータス確認
- ロール確認 => チーミングのステータス確認

それぞれsection4-1, 4-2, 4-3に相当します。

2020-08-29 15:45 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section4-1.md
> +そのため、振り返りはテンショントリアージと違いある程度まとまった期間をおいて実施するものであり、またその分必要な時間もテンショントリアージよりも長くなります。ただし、この「まとまった期間」は、「何かのマイルストーンが終わったあとに実施する」といったようなものではなく、「何週間おき」「何か月おき」といったような定期的な時間で設定してください。これは、最適化ができずにマイルストーンがいつまでも達成で
@motoi 

読点いれました。
eda9158e580657dad8c8d65dc232bf24fda1819b

フェーズ終わりのほうなんですが推奨する理由について少し材料もらえますか？これまでの議論でも自分がいまいちぴんと来ていないことに気づきました。「キリがいいからやっておく」っていう以外にあんまり説明ができず、それもそうなのかなと思いつつ、なんかぼやっとした理解な気がしていて。

そこのところはファイル読んでもやっぱりよくわからず…ちょっと素材をもらえると助かります。

2020-08-29 15:49 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section4-3.md
> +ロールの確認をするべきタイミングは、次のような時です。
@motoi 
> ロールに関するテンションがあがるよね、という話題もあるとおもうけど、
すみません、引っかかっているポイントがよくわからないのですが、

secton3-2のテンショントリアージの手続きの中でロールに関するテンションが上がり、ロール確認のアジェンダになります。この全体の流れが、section4-3でいう1~4のどれかにあたります。

いちおうロール確認とテンションの関係でいうとこんな感じです。

整理はされていると思うので、対応はなしでいいかと。

2020-08-29 15:58 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section5-1.md
> +
@motoi 
なるほど。こんな感じでしょうか。
3505e1c509073b7c8e3a88b02c322546f7b880a8

2020-08-29 16:00 UTC, Satoshi-Matsumoto commented on ja/manual/tips/index.md
> +6. [ ロールシートの利用](tips6.md)
@motoi 
なおしました。この辺の絶対直すだろ系はそのまま修正コミットしてもらっても大丈夫です。
450eef7aa815c6b53abb41e01b4a73b682d43bd8

2020-08-29 16:02 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips1.md
> +
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479560869
と同じことを言っていると思うのでこっちはResolveします。

2020-08-29 16:05 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips1.md
> +
@motoi 
全面同意なんですがv0.8.0のリリース日までの納期で、ってのは厳しい気がしたのでissue化しておきました。
#141  
です。進行は別途進めるのでここではissue化されたことを確認してResolveお願いします。

2020-08-29 16:45 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips1.md
> +#### イベント - 作業の直接の進行とは関係ない重要行事
@motoi 
読んでいてイベントという概念の位置づけに対する理解は変わらないかなと思いました。
言われている通り「直接の進行と関係ない」の表現の問題かなと思います。

プロジェクトの外で起こるものです、というところがポイントかなと思っていて、逆にここでいうところの「プロジェクトの中」って何かっていうと、マイルストーンおよびそれに向けての（＝成果物をつくるための）実行作業全般、のことになると思うんですよね。で、それらがプロジェクトの作業に直接関係するもの、と捉えています。

というわけで、そのあたりのニュアンスを取りいれつつ、「直接」とかいった表現を使わない修正を加えてみました。

6290b02b3033918378b98e862c936df10cb95ccf

2020-08-29 16:53 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips1.md
> +しかし、プロジェクトでのコミュニケーション上は、いま自分たちは何をしているのか？ということを表現できたほうが便利です。このそれぞれを、「フェーズ」と呼びます。つまり、この例では、
@motoi 
ba114e14bf1ea30673b3cc3274754d695ee3a0a6
修正しました。
ちなみに、

> もっというと自分たちのメンバーは何書いてもある程度はわかるので、ほかのチームメンバーが読んで何をやってるのかわかるということの方が重要だとおもっています。

これはトラックがあること前提になっている表現だと思いますが、そのうえで、自分たちのチーム、ほかのチーム、というのはあまりこれまでCODEやマニュアルで使わっていない表現だとおもうので、避けています。

2020-08-29 17:00 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips10.md
> +Section3-2で解説したように、ミーティング開始時にはテンショントリアージを実施します。これによって、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などを共有し、解決のためのアクションにつなげることができるようになります。
@motoi 
テンションがあがる => その後のアジェンダトリアージのための材料が出てくる
という考え方からすると開始時にする必要があると思います。

ただ、同じような位置づけにあるのがタスク確認（タスク進捗報告）で、その後にはなると思います。

とはいえsection3-2でも

> ミーティングの最初に、タスクの進捗報告とテンショントリアージを行ってください。

こういう併記の仕方をしているので開始時、と書いて問題ないと思いましたがどうでしょう？

ミーティング冒頭のタスクの進捗報告を超えた報告アジェンダみたいなもののあとにテンショントリアージをする、というのであれば、どちらかというと個別案件のカスタマイズの範囲なのかと思います。

2020-08-29 17:05 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips10.md
> +  - 他メンバーへのタスクのリクエスト
@motoi 
「タスクのリクエスト」から自分にリクエストする、というニュアンスを読み取るのも難しいかなと思ったので、下記のように修正しました。また、これは「自分が必要としていること」でもないと思うのでそのあたりも変な表現にならないように修正しました。

1323986980a1ceca2228962414661a03dc888184

2020-08-29 17:09 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips10.md
> +テンショントリアージは、次のような手順で実施します。
@motoi 
なるほど、こんな感じのニュアンスでしょうか。
3815f4397ce4e620e7c79cd146f215e9b8a26d55

2020-08-29 17:10 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips2.md
> +
@motoi 
何かしらの図があるとわかりやすいのはそうだと思うんですが、どういうことを示す概念図が必要かちょっとわからないので、issue化お願いできますか？issue立てていただいたあと、こちらはResolveお願いします。

2020-08-29 17:18 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips3.md
> +成果物は、マイルストーン完了の際につくられているべきもののことを指します。成果物はアウトカムによって構成されています。
@motoi 
まずこのTipsが必要がだった理由は、CODEのベーシックに入れている内容は網羅しようと思ったからですね。[理論編に入っている内容](https://projectsprint.org/ja/theory/basic.html)になります。
ただチュートリアルの流れに入れる必要はなくて、その意味でTipsとしていれました。

ちなみにCODEの中のアウトカム(成果)の概念は一応この辺でやり取りした内容をもとに書いてます。
https://github.com/copilot-jp/project-sprint/issues/23#issuecomment-631298875
https://github.com/copilot-jp/project-sprint/issues/23#issuecomment-635968058
PJS概念図との整合性も踏まえつつ、必要な概念となってます。

2020-08-29 17:22 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips9.md
> +一般的な「振り返り」の手法は様々なものがありますが、ここでは比較的簡単に導入でき、汎用性も高い二つの手法を例として紹介します。
@motoi 
実はYWTやったことなく…まとめてる資料も読ませてもらったので推測で書いてみることもできるんですが、できれば一回やったあとで書きたいです。というわけでissue化しておいて、実際やった後に加えるかも含めて検討する流れにさせてください。

2020-08-29 17:24 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips9.md
> +一般的な「振り返り」の手法は様々なものがありますが、ここでは比較的簡単に導入でき、汎用性も高い二つの手法を例として紹介します。
@motoi 
下記たてたのでissue化されていることを確認したらこちらはResolveにしてください。
https://github.com/copilot-jp/project-sprint/issues/142

2020-08-29 17:26 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips9.md
> +プロジェクトスプリントにおける振り返りとはチームメンバーが過去のプロジェクトの内容についてレビューする取り組みです。
@motoi 
自分の中で当たり前すぎて抜けてたという感じですが、書いたほうがいいですね…
b6b71cd73861071c7a360dc35c8194a4f9139833
いれました。

2020-08-29 17:27 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips7.md
> +アジェンダ管理に不可欠な前提がミーティング中の時間を的確に把握することです。オンライン / オフラインいずれの場合も、ミーティングに参加しているチームメンバーが時間を把握できるよう、目に入る位置にタイマーを把握しましょう。
@motoi 
配置です。
20ec99434680703982a7a416cd6b1d61ba0a73fd

2020-08-29 17:30 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips7.md
> +なお、ミーティング中は「いま何時か」ではなく、「このミーティングはあとどのくらいあるのか」「このアジェンダにあとどれくらい時間をかけられるのか」を把握することが必要になるため、現在時刻を示す時計よりもタイマーを利用したほうがよいとされています。
@motoi 
ミーティングの全体時間を把握するのもタイマーじゃないですか？(「2時間」とか「1.5時間」とか枠で把握するので）
このミーティングはあとどのくらいあるのか => ミーティングの全体時間を把握するタイマー
と
このアジェンダにあとどれくらい時間をかけられるのか => 個別アジェンダの時間を把握するタイマー
の2種類がいる
という話かと思います。ただタイマー何種類用意しろ、はさすがに細かすぎるので（SGMsみたいな一括管理するツールもあるし）そこは書いてないです。

絶対時間としての時計が必要なのはむしろミーティング中の時間管理ではなく、スケジュール調整の時だと思います。

2020-08-29 17:37 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips7.md
> +なおここでいうとホワイトボードはオフライン会議における物理的なものに限りません。オンライン会議用のホワイトボードツールもありますので、そういったものを利用してもかまいませんし、むしろ保存のしやすさという点ではこちらのほうが優れている場合もあります。
@motoi 
活字形式のリアルタイムに反映される認識の合わせツール　については議事録パートがそれに相当すると思います。

> ミーティングはチームメンバーで認識のズレをなくし、必要な物事を決める重要な場です。ミーティングの間に各自が必要なタスクに取りかかり、次のミーティングでその結果を持ち寄ることを考えると、ミーティングの内容は極力ミーティングの最中に明文化しながら確認、共有しておくことが効率的かつ効果的です。また、レコーダーがメインで議事を記録するものの、内容に間違いがある場合は最も正しい認識を持つ人がその場で修正してしまったほうがよいでしょう。

> そのため、共同編集ができるドキュメントツールを議事録作成用ツールとして導入し、ミーティング中に画面表示しながらリアルタイムで議事録作成をすることをおすすめします。

そのうえで、ホワイトボードはやはり手書き入力ツールとしての重要性を示すものとして書いています。
名称としては

https://gsuite.google.co.jp/intl/ja/products/jamboard/
https://utilly.jp/2019/03/31/about-miro/
https://www.microsoft.com/ja-jp/microsoft-365/microsoft-whiteboard/digital-whiteboard-app

この辺りが自らをホワイトボードといっていることもあり、そのままのほうがいいと思います。（結局この辺りのツール使うと思うので）

そもそもこのTips全体がベストプラクティスという位置づけで書いてますし、手書き用ツール絶対使えっていうことでもないので、いまのままでいいんじゃないかと。

2020-08-29 17:40 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips4.md
> +ここで話す内容は一般的にプロジェクト管理で語られる要素と大きく異なりません。しかし、プロジェクトスプリントでは、それらの要素すべてにおいて、「コミュニケーションの透明性をいかに担保するか」という点を中心に考えるべきです。
@motoi 
たしかに。情報に一本化するのがシンプルかつ誤解もないですかね。
519b9e0669dddc3b387880f895a974bc6a2a612c

2020-08-29 17:43 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips4.md
> +- ファイル管理: プロジェクトメンバーが誰でもアクセスできるファイル管理環境を用意しましょう。
@motoi 
異論なしです。
05e323def791b08866847aa89a0f20b1456ab1f9

2020-08-29 17:48 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips4.md
> +- スケジュール管理: スケジュール調整に必要な限りで、メンバー間の個人カレンダーを共有するようにしましょう。これは、メールなどによって都度日程調整をするのではなく、チームメンバーのスケジュール状況が一か所に集まっており、必要な人が必要なときに見に行ける環境を意味しています。
@motoi 
なるほど。取り入れました。
ecf7371c633169ad9c6866993a78f7655b09afd0

2020-08-29 17:54 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips4.md
> +その他、プロジェクトスプリントにおける3つのドメインおいて必要とされる環境 - マイルストーン管理（プログレス）、ロール管理（チーミング）、ミーティング管理（プロセス）、については、それぞれ別Tipsをご参照ください。
@motoi 
私個人の感覚かもしれませんが
> 管理という言葉だと誰か一人がコントロールして、計画通りにする感が大きい。
これは自分としてはそんなに思わないんですよね。きちんと把握して運用しようよ、くらいの厳しさで、そこまでなんか支配的？なニュアンスを持ってないです。

一方いろんな資料見てると結構普通に「～～管理」というのは使われていて（プロジェクスプリント設定シートのテンプレートとかに顕著です）、みんなもそこまで忌避するべきニュアンス持ってないんじゃないかとも思ってます。

そう思うと、CODEならともかく、マニュアルで、かつTipsでそこを厳密にみてわかりにくくしてしまうのもな、という気もしています。

とか私個人の感覚だと思ったりするんですがどうですか？納得いかん！ということであればissue化して継続議論にさせてもらえればと。

2020-08-29 17:58 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips5.md
> +ただし、次に紹介するようなロールについては実務上よく使われるであろう予め用意されており、特にプロジェクトスプリントを始めて導入する場合、これらのロールを利用することによって導入をスムーズに行うことができます。
@motoi 
確かに日本語変ですね。。。。直しました。
8f682761dd1ec670043e1cccf4458e924cdfcc79

一応補足ですが、
> ・実務上必要なロールは定義しているから必要であれば使ってね
必要って言っちゃうと必須(Plug-inではなくEssential)になってしまうので、あくまで「よく使う」ていでこだわってかいておりやす。

2020-08-30 08:47 UTC, kikuchiharuma commented on ja/manual/tutorial/section5-1.md
> +#### ユーザーコミュニティ
@motoi いえ、大丈夫です！Resolveします。
が、急いでライセンスの文書をこのプルリクに合流させないといけないですね

2020-08-30 12:39 UTC, motoi commented on ja/manual/tips/tips1.md
> +しかし、プロジェクトでのコミュニケーション上は、いま自分たちは何をしているのか？ということを表現できたほうが便利です。このそれぞれを、「フェーズ」と呼びます。つまり、この例では、
@Satoshi-Matsumoto 
修正先を読んでのコメントです。複数チームについての言及は避けているけど今回は表現してくれている、ということでよいですよね。

プロジェクトに複数チームが存在することは普通におこっていることだとおもうので、複数チームが存在する場合のことを書くのはよいかなとおもっています。
で、その複数チームのことをトラックと表現するかどうかは判断だなと思いました。
個人的には、トラックはエッセンシャルズに入っている概念でもないので、他のチームのメンバーが、みたいな表現でも違和感はないかなとおもいました。

どうでしょ？

2020-08-30 12:49 UTC, motoi commented on ja/manual/tips/tips10.md
> +Section3-2で解説したように、ミーティング開始時にはテンショントリアージを実施します。これによって、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などを共有し、解決のためのアクションにつなげることができるようになります。
@Satoshi-Matsumoto さん
多くの場合は、最初なり開始時に行うことが多いというニュアンスならわかります。
またホラクラシーのタクティカルミーティングはテンショントリアージが開始時じゃないので、あのスタイルのMTGを行う人だと、開始時、には違和感が出ると思うのです。

ですが、PJSにおいてテンショントリアージのベストプラクティスができってる感じもしないので、もう少しケースが出せたらそれに合わせて調整ということでお願いします。ということでいったんリゾルブ。

2020-08-30 12:51 UTC, kikuchiharuma approved these changes
最&高

2020-08-30 12:54 UTC, motoi commented on ja/manual/tips/tips10.md
> +  - 他メンバーへのタスクのリクエスト
@Satoshi-Matsumoto 
これで選択肢が1つ増えるほうが煩雑になると感じるので、これであれば元のままで大丈夫です。先ほどもコメントしましたがテンショントリアージのベストプラクティスがもう少しでたら調整させてください。

2020-08-30 13:09 UTC, motoi commented on ja/manual/tips/tips2.md
> +
マイルストーンマップはPJSの中でも重要な要素ですが、構造が分かりづらいので図で表現したほうが構造を理解しやすいとおもっています。
![image](https://user-images.githubusercontent.com/680855/91659758-e148c900-eb0c-11ea-918a-dccb86c137da.png)
とか
![image](https://user-images.githubusercontent.com/680855/91659788-0fc6a400-eb0d-11ea-9a6f-bb21b9677c56.png)
とかの絵が私たちは頭に入っているので、この文章が読めるんだと感じます。

なのでこのようにマイルストーンマップという抽象的な概念を絵にしたほうがりかいしてもらいやすいのでは？という提案です。

2020-08-30 13:16 UTC, motoi commented on ja/manual/tips/tips3.md
> +プロジェクトでは様々なものが生み出されますが、そのそれぞれの持つ意味合いや粒度によって名称を区別することは、チームメンバー間の子コミュニケーションをスムーズにし、プロジェクトの成功を助けてくれます。
> チームメンバー間の子コミュニケーションをスムーズにし、

タイポかな。
チームメンバー間のコミュニケーションをスムーズにし、

2020-08-30 13:36 UTC, motoi commented on ja/manual/tips/tips3.md
> +成果物は、マイルストーン完了の際につくられているべきもののことを指します。成果物はアウトカムによって構成されています。
@Satoshi-Matsumoto 
私が成果という言葉でずっと認識していた、かつ、成果はとても概念的なものとしてとらえていたので、アウトカムのこの説明をとても具体的なつくりだされるものとして読んでいたので、別モノと感じていました。

概念の説明であることと、その目線で読み返すと理論編との整合性はとれているので、いったんリゾルプとさせてもらいます。

2020-08-30 13:46 UTC, motoi commented on ja/manual/tips/tips4.md
> +その他、プロジェクトスプリントにおける3つのドメインおいて必要とされる環境 - マイルストーン管理（プログレス）、ロール管理（チーミング）、ミーティング管理（プロセス）、については、それぞれ別Tipsをご参照ください。
私も3つ並ぶまであんまり感じなかったんだよね。
とりあえず私のコメントでイシュー化して今回のリリースとしてはいったんこれで。

2020-08-30 14:00 UTC, motoi commented on ja/manual/tips/tips7.md
> +なお、ミーティング中は「いま何時か」ではなく、「このミーティングはあとどのくらいあるのか」「このアジェンダにあとどれくらい時間をかけられるのか」を把握することが必要になるため、現在時刻を示す時計よりもタイマーを利用したほうがよいとされています。
タイマーを複数個用意しようという意味ではないです。絶対時刻を表示する時計があったほうが良いという話です。

その理由です。

・ミーティングが遅れて/はやめに始まることがあるので、絶対時刻を把握するものがあったほうがよい。
・タイマーが鳴っても多少そのままアジェンダを延期する場合があるので、ものすごく厳密にタイマーを管理しないかぎり、タイマーの時間の総和が会議の時間になることはない。
・会議を延長する際に、何時まで伸ばします？みたいな会話の時も現在時刻がわかるものが欲しい。

この観点で時刻がわかる時計とタイマーがあったほうが良いなとおもっています。

2020-08-30 14:04 UTC, motoi commented on ja/manual/tips/tips7.md
> +#### ホワイトボード
ここにコメント書いてたんだけど消えてるな。。。
これホワイトボードだとフィジカルなモノが想起されすぎる感があるなと。
本文中ではフォローしてくれているけどタイトルの雰囲気を変えたい。
「手書き入力により認識合わせするツール」
みたいなタイトルでなんかよい感じにできないですかね。

2020-08-30 14:05 UTC, motoi commented on ja/manual/tips/tips9.md
> +一般的な「振り返り」の手法は様々なものがありますが、ここでは比較的簡単に導入でき、汎用性も高い二つの手法を例として紹介します。
確認しました。リゾルブで。

2020-08-30 14:19 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +ゴールは、最初のドラフトは誰がつくってもかまいませんし、一人でもつくっても複数で作ってもかまいませんが、通常は、
実務で一番多いパターンは、
ゼロからみんなで議論するして、発散的に意見をみんなでだし、なんとなくマイルストーンの形が見える
ぐらいまでミーティングで行い、その精査やら整理を誰かが作業してきて、チームメンバーみんなで改めて議論する、という流れが一番おおいかなとおもいます。
いきなり誰かがたたき台をもってくるというのはほぼないんじゃないかしら。

このコメントを考えてみて、チュートリアルやチップスは、理想の流れと、実際にはどういうケースが多い、というものを明確にしながら並記するのがよいんじゃないかとおもいました。

2020-08-30 14:26 UTC, motoi commented on ja/manual/tutorial/section2-3.md
> +なお、各ミーティングの参加者はアジェンダに応じて必要十分な程度でかまいません。ここでいう必要十分とは、アジェンダに関して網羅的に議論でき（＝「誰かがいないから今日はこの話ができないね」ということがないようにする）、また議論をもとに正式な意思決定ができること（＝「誰かがいないから今日はこの話は決まらないね」ということがないようにする）を意味しています。
イシュー確認しましたー。

2020-08-30 14:52 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +設定したゴールとマイルストーンは、いつでもチームメンバーが参照できる状態にしておきます。
プロジェクトにおける足並みを揃えた実績としては以下のようなものです。

・広報チームのマイルストーンに合わせて、他のチームが自発的にアウトプットを用意する
・プロダクトチームの進捗状況に合わせて、プロダクトのデリバリーチームが自分たちの取るべき行動を変えていく

もっと詳しく書いたほうが良いかしら？

2020-08-30 21:46 UTC, motoi commented on ja/manual/tutorial/section5-1.md
> +
現状だと問題ないと思いました。
orgの方にコントリビューターの記述が表示されたらそちらに移行するんだと思いますけど。
ということでリゾルブで。

2020-08-30 21:48 UTC, motoi commented on ja/manual/tutorial/section4-3.md
> +ロールの確認をするべきタイミングは、次のような時です。
ではまた違和感があったら上げますのでリゾルブで。

2020-08-30 21:50 UTC, motoi commented on ja/manual/tutorial/section4-1.md
> +プロジェクトスプリントではミーティングを通じて継続的にプロジェクトの進め方を改善すること（最適化）を目指しています。これらの最適化のため取り組みを総称して「継続的改善アプローチ」と呼んでおり、これはさらに「テンショントリアージ」と「振り返り」という二つの取り組みに分けられます。
これはテンションがもうちょっと見えたらその議論しましょうか。
テンションをあげるにはロールがあったほうがよりあげやすいとおもっていて。
別イシュー化してリゾルブしておきます。

2020-08-30 21:52 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +----
了解す。リゾルブで。

2020-08-30 21:54 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
@Satoshi-Matsumoto リンク先にコメントしたタイポを修正してくださいー。

2020-08-30 21:55 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
確認しました。

2020-08-30 21:56 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
確認しました。

2020-08-30 21:57 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
確認しました。
全体的に手順ぽくなっているところが多いので、冒頭に目的を書くといまよりももっと読みやすくなる可能性を感じました。

2020-08-30 21:59 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +テンションとは、「プロジェクトを過ごす中で他のメンバーに伝えたい違和感」のことです。具体的には、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などのことを指します。
トリアージの意味は確認しました。
テンションの目的はもうちょっと精査されてきたら記入を検討させてください。
運用上これを意識するかしないかでファシリテーターの行動が全然変わるのでその辺もまとまったらまた検討ということで。

2020-08-30 22:00 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
たしかに。リゾルブで。

2020-08-30 22:02 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
確認しました。

2020-08-30 22:03 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +マイルストーンも、ゴール同様最初のドラフトは誰がつくってもかまいませんし、一人でつくっても複数でつくってもかまいません。
132の状況により対応検討（返信してるよというメモ）

2020-08-31 10:25 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +
@Satoshi-Matsumoto 
自分で修正しました。リゾルプで。

2020-08-31 10:26 UTC, motoi commented on ja/manual/tips/tips3.md
> +プロジェクトでは様々なものが生み出されますが、そのそれぞれの持つ意味合いや粒度によって名称を区別することは、チームメンバー間の子コミュニケーションをスムーズにし、プロジェクトの成功を助けてくれます。
@Satoshi-Matsumoto 
自分で修正しました。リゾルブで。

2020-08-31 11:53 UTC, motoi commented on ja/manual/tips/tips1.md
> +しかし、プロジェクトでのコミュニケーション上は、いま自分たちは何をしているのか？ということを表現できたほうが便利です。このそれぞれを、「フェーズ」と呼びます。つまり、この例では、
https://github.com/copilot-jp/project-sprint/issues/147
こちらにイシュー化したのでとりあえずリゾルブ。

2020-08-31 11:56 UTC, motoi commented on ja/manual/tips/tips7.md
> +なお、ミーティング中は「いま何時か」ではなく、「このミーティングはあとどのくらいあるのか」「このアジェンダにあとどれくらい時間をかけられるのか」を把握することが必要になるため、現在時刻を示す時計よりもタイマーを利用したほうがよいとされています。
@Satoshi-Matsumoto さん
https://github.com/copilot-jp/project-sprint/issues/148
イシュー化しておきましたので別途議論ってことでいったんリゾルブ。

2020-08-31 11:59 UTC, motoi commented on ja/manual/tips/tips7.md
> +#### ホワイトボード
https://github.com/copilot-jp/project-sprint/issues/149
こっちでイシュー化したので続きはこちらで！

2020-08-31 12:17 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2/section2-1.md
> +プログレスドメインの「理想の状態」とは、プロジェクトのゴールが達成されている状態です。そのため、まずは将来達成したいプロジェクトのゴールを定義し、そのために必要な成果物と、成果物をつくっていくための道のり（これを、マイルストーンと呼びます）を設定します。
@motoi 閉じてしまいます。

2020-08-31 12:21 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-1.md
> +ゴールは、最初のドラフトは誰がつくってもかまいませんし、一人でもつくっても複数で作ってもかまいませんが、通常は、
https://github.com/copilot-jp/project-sprint/issues/150
でイシューにしました。こちらはいったん閉じます。

2020-08-31 12:25 UTC, Satoshi-Matsumoto commented on ja/manual/tutorial/section2-1.md
> +マイルストーンも、ゴール同様最初のドラフトは誰がつくってもかまいませんし、一人でつくっても複数でつくってもかまいません。
こちらも
https://github.com/copilot-jp/project-sprint/issues/150
と同様に進めます。

2020-08-31 12:25 UTC, motoi commented on ja/manual/tutorial/section2-3.md
> +まず、ミーティングは定例会議である必要があります。これには理由が二つあります。一つ目は、ある程度以上の複雑性があるプロジェクトでは、都度チームメンバーを招集していては必要な議論がタイムリーにできない可能性があるということ。二つ目は、週次や月次といった一定の期間における開催とすることで、プロジェクトの状態を定期的にチェックし、必要な時に見直すことができるということです。
あざす！

2020-08-31 12:28 UTC, motoi commented on ja/manual/tutorial/section2-2.md
> +- それぞれのメンバーは、どのような人ですか？例えばスキルセットは、どのようなものがありますか？これまえにどのような仕事にかかわってきましたか？
おけっす。次からこの手のは自分で治します。

2020-08-31 12:28 UTC, motoi commented on ja/manual/tutorial/section3-1.md
> +なお、プロジェクトスプリントではモデレーターとアクセラレーターの二つをまとめてファシリテーターと定義しています。
あざす！

2020-08-31 12:29 UTC, motoi commented on ja/manual/tutorial/section3-1.md
> +毎回のミーティングが始まる前には、予め各チームメンバーがアジェンダを提出します。アジェンダには、少なくとも次のような内容が含まれている必要があります。
あざす！

2020-08-31 12:29 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +ミーティングの最初に、タスク確認とテンショントリアージを行ってください。これらを通じて、前回のミーティングから今回のミーティングまでに、実際の作業や気持ちの面のそれぞれで起こったことについて、チームメンバー同士でアップデートを行い、必要であれば新たなタスク化/アジェンダ化して対処することができます。
あざす！

2020-08-31 12:30 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +#### タスク確認とテンショントリアージ
イシュー化を確認しました！

2020-08-31 12:33 UTC, motoi commented on ja/manual/tutorial/section4-1.md
> +そのため、振り返りはテンショントリアージと違いある程度まとまった期間をおいて実施するものであり、またその分必要な時間もテンショントリアージよりも長くなります。ただし、この「まとまった期間」は、「何かのマイルストーンが終わったあとに実施する」といったようなものではなく、「何週間おき」「何か月おき」といったような定期的な時間で設定してください。これは、最適化ができずにマイルストーンがいつまでも達成で
https://github.com/copilot-jp/project-sprint/issues/152
とりあえずイシュー化したのでリゾルブで。

2020-08-31 12:34 UTC, motoi commented on ja/manual/tips/tips7.md
> +なおここでいうとホワイトボードはオフライン会議における物理的なものに限りません。オンライン会議用のホワイトボードツールもありますので、そういったものを利用してもかまいませんし、むしろ保存のしやすさという点ではこちらのほうが優れている場合もあります。
納得したのでリゾルブで。

2020-08-31 12:35 UTC, motoi commented on ja/manual/tips/tips4.md
> +- ファイル管理: プロジェクトメンバーが誰でもアクセスできるファイル管理環境を用意しましょう。
確認済み。リゾルブ。

2020-08-31 12:36 UTC, motoi commented on ja/manual/tips/index.md
> +6. [ ロールシートの利用](tips6.md)
次から自分でやりますー。

2020-08-31 12:38 UTC, motoi commented on ja/manual/tips/tips5.md
> +ただし、次に紹介するようなロールについては実務上よく使われるであろう予め用意されており、特にプロジェクトスプリントを始めて導入する場合、これらのロールを利用することによって導入をスムーズに行うことができます。
確認しましたー。

2020-08-31 12:38 UTC, motoi commented on ja/manual/tips/tips4.md
> +- スケジュール管理: スケジュール調整に必要な限りで、メンバー間の個人カレンダーを共有するようにしましょう。これは、メールなどによって都度日程調整をするのではなく、チームメンバーのスケジュール状況が一か所に集まっており、必要な人が必要なときに見に行ける環境を意味しています。
確認しました！

2020-08-31 12:39 UTC, motoi commented on ja/manual/tips/tips4.md
> +ここで話す内容は一般的にプロジェクト管理で語られる要素と大きく異なりません。しかし、プロジェクトスプリントでは、それらの要素すべてにおいて、「コミュニケーションの透明性をいかに担保するか」という点を中心に考えるべきです。
確認しました！

2020-08-31 12:41 UTC, motoi commented on ja/manual/tutorial/section3-2.md
> +なお、すでに予めタスクとしてリストアップされていたり、アジェンダとして提出されていた場合は、ここでさらに追加する必要はありません。
了解ー。ではいったんこれで！

2020-08-31 12:41 UTC, motoi commented on ja/manual/tips/tips1.md
> +#### イベント - 作業の直接の進行とは関係ない重要行事
めちゃよくなったとおもいます！

2020-08-31 12:42 UTC, motoi commented on ja/manual/tips/tips10.md
> +テンショントリアージは、次のような手順で実施します。
よいとおもいます！

2020-08-31 12:42 UTC, motoi commented on ja/manual/tips/tips7.md
> +アジェンダ管理に不可欠な前提がミーティング中の時間を的確に把握することです。オンライン / オフラインいずれの場合も、ミーティングに参加しているチームメンバーが時間を把握できるよう、目に入る位置にタイマーを把握しましょう。
次から自分でやります！おす！

2020-08-31 12:42 UTC, motoi commented on ja/manual/tips/tips9.md
> +プロジェクトスプリントにおける振り返りとはチームメンバーが過去のプロジェクトの内容についてレビューする取り組みです。
確認しました！

2020-08-31 12:46 UTC, motoi commented on ja/manual/tutorial/section2-1.md
> +設定したゴールとマイルストーンは、いつでもチームメンバーが参照できる状態にしておきます。
https://github.com/copilot-jp/project-sprint/issues/153
イシュー化あんどリゾルブ

2020-08-31 12:47 UTC, motoi approved these changes
これでお願いします！

2020-08-31 12:58 UTC, Satoshi-Matsumoto commented on ja/manual/tips/tips2.md
> +
https://github.com/copilot-jp/project-sprint/issues/143　へ

2020-08-31 13:15 UTC, Satoshi-Matsumoto commented
@motoi 
ありがとうございます。
https://github.com/copilot-jp/project-sprint/pull/132#commitcomment-41890448
こちらはなおしました。
62f7f77ddce0a5ece135ed7fceb4c92fdfee19de

https://github.com/copilot-jp/project-sprint/pull/132#commitcomment-41890165
の流れは、下記のissueで。
https://github.com/copilot-jp/project-sprint/issues/154

2020-08-31 14:00 UTC, merged